[profile.default]
src = "src"
test = "test"
out = "out"
cache_path = "cache"

solc = "/usr/local/bin/solc"
optimizer = true
optimizer_runs = 200

ffi = true

[profile.default.fuzz]
runs = 1024

fs_permissions = [
  { access = "read", path = "./" },
  { access = "read-write", path = "./out" },
]
